// ── Exchanges ─────────────────────────────────────────────────
const EXCHANGES = {
    NYSE:   { flag: '', fullName: 'New York Stock Exchange' },
    NASDAQ: { flag: '', fullName: 'NASDAQ' },
    LSE:    { flag: '', fullName: 'London Stock Exchange' },
    TSE:    { flag: '', fullName: 'Tokyo Stock Exchange' },
    HKEX:   { flag: '', fullName: 'Hong Kong Stock Exchange' },
    NSE:    { flag: '', fullName: 'National Stock Exchange of India' },
    CRYPTO: { flag: '',   fullName: 'Crypto Market' },
};

// ── Stock data ────────────────────────────────────────────────
// [ticker, company, exchange, basePrice (coins), volatility]
const STOCKS_RAW = [
    // ── NYSE (50) ─────────────────────────────────────────────
    ['BRK',  'Berkshire Hathaway',       'NYSE', 4800, 0.025],
    ['JPM',  'JPMorgan Chase',           'NYSE',  220, 0.035],
    ['V',    'Visa Inc.',                'NYSE',  280, 0.030],
    ['WMT',  'Walmart',                  'NYSE',  180, 0.025],
    ['JNJ',  'Johnson & Johnson',        'NYSE',  160, 0.025],
    ['PG',   'Procter & Gamble',         'NYSE',  170, 0.022],
    ['MA',   'Mastercard',               'NYSE',  480, 0.032],
    ['BAC',  'Bank of America',          'NYSE',   45, 0.040],
    ['XOM',  'ExxonMobil',               'NYSE',  110, 0.045],
    ['CVX',  'Chevron',                  'NYSE',  160, 0.040],
    ['HD',   'Home Depot',               'NYSE',  380, 0.030],
    ['MRK',  'Merck & Co.',              'NYSE',  130, 0.030],
    ['ABBV', 'AbbVie',                   'NYSE',  180, 0.035],
    ['LLY',  'Eli Lilly',                'NYSE',  800, 0.040],
    ['PFE',  'Pfizer',                   'NYSE',   28, 0.040],
    ['KO',   'Coca-Cola',                'NYSE',   62, 0.020],
    ['PEP',  'PepsiCo',                  'NYSE',  170, 0.022],
    ['MCD',  "McDonald's",               'NYSE',  290, 0.025],
    ['DIS',  'Walt Disney',              'NYSE',   95, 0.050],
    ['COST', 'Costco Wholesale',         'NYSE',  870, 0.025],
    ['TMO',  'Thermo Fisher',            'NYSE',  550, 0.030],
    ['ABT',  'Abbott Laboratories',      'NYSE',  110, 0.028],
    ['UNH',  'UnitedHealth Group',       'NYSE',  580, 0.030],
    ['DHR',  'Danaher Corp',             'NYSE',  230, 0.032],
    ['TXN',  'Texas Instruments',        'NYSE',  200, 0.038],
    ['GE',   'GE Aerospace',             'NYSE',  170, 0.045],
    ['HON',  'Honeywell',                'NYSE',  210, 0.030],
    ['MMM',  '3M Company',               'NYSE',  125, 0.040],
    ['BA',   'Boeing',                   'NYSE',  185, 0.065],
    ['CAT',  'Caterpillar',              'NYSE',  370, 0.040],
    ['DE',   'Deere & Company',          'NYSE',  440, 0.038],
    ['UPS',  'United Parcel Service',    'NYSE',  140, 0.035],
    ['FDX',  'FedEx',                    'NYSE',  240, 0.042],
    ['RTX',  'RTX Corporation',          'NYSE',  115, 0.035],
    ['LMT',  'Lockheed Martin',          'NYSE',  520, 0.028],
    ['GS',   'Goldman Sachs',            'NYSE',  490, 0.040],
    ['MS',   'Morgan Stanley',           'NYSE',  115, 0.038],
    ['AXP',  'American Express',         'NYSE',  230, 0.035],
    ['BLK',  'BlackRock',                'NYSE',  960, 0.032],
    ['C',    'Citigroup',                'NYSE',   68, 0.042],
    ['WFC',  'Wells Fargo',              'NYSE',   64, 0.040],
    ['USB',  'U.S. Bancorp',             'NYSE',   48, 0.038],
    ['TGT',  'Target Corp',              'NYSE',  150, 0.040],
    ['SBUX', 'Starbucks',                'NYSE',   95, 0.045],
    ['NKE',  'Nike',                     'NYSE',   75, 0.040],
    ['CL',   'Colgate-Palmolive',        'NYSE',   95, 0.022],
    ['PM',   'Philip Morris',            'NYSE',   95, 0.028],
    ['MO',   'Altria Group',             'NYSE',   48, 0.030],
    ['T',    'AT&T',                     'NYSE',   17, 0.030],
    ['VZ',   'Verizon',                  'NYSE',   40, 0.028],

    // ── NASDAQ (50) ───────────────────────────────────────────
    ['AAPL', 'Apple Inc.',               'NASDAQ', 190, 0.035],
    ['MSFT', 'Microsoft',                'NASDAQ', 420, 0.032],
    ['NVDA', 'NVIDIA',                   'NASDAQ', 880, 0.070],
    ['AMZN', 'Amazon',                   'NASDAQ', 185, 0.045],
    ['GOOGL','Alphabet',                 'NASDAQ', 170, 0.038],
    ['META', 'Meta Platforms',           'NASDAQ', 520, 0.050],
    ['TSLA', 'Tesla',                    'NASDAQ', 250, 0.090],
    ['AVGO', 'Broadcom',                 'NASDAQ',1400, 0.045],
    ['ASML', 'ASML Holding',             'NASDAQ', 980, 0.050],
    ['AMD',  'Advanced Micro Devices',   'NASDAQ', 175, 0.070],
    ['ORCL', 'Oracle',                   'NASDAQ', 140, 0.040],
    ['CSCO', 'Cisco Systems',            'NASDAQ',  54, 0.028],
    ['ADBE', 'Adobe',                    'NASDAQ', 540, 0.045],
    ['QCOM', 'Qualcomm',                 'NASDAQ', 165, 0.050],
    ['INTC', 'Intel',                    'NASDAQ',  25, 0.060],
    ['NFLX', 'Netflix',                  'NASDAQ', 640, 0.055],
    ['PYPL', 'PayPal',                   'NASDAQ',  62, 0.060],
    ['INTU', 'Intuit',                   'NASDAQ', 680, 0.040],
    ['AMAT', 'Applied Materials',        'NASDAQ', 220, 0.055],
    ['MU',   'Micron Technology',        'NASDAQ', 115, 0.065],
    ['KLAC', 'KLA Corp',                 'NASDAQ', 750, 0.050],
    ['LRCX', 'Lam Research',             'NASDAQ', 920, 0.050],
    ['SNPS', 'Synopsys',                 'NASDAQ', 520, 0.045],
    ['CDNS', 'Cadence Design',           'NASDAQ', 310, 0.045],
    ['PANW', 'Palo Alto Networks',       'NASDAQ', 370, 0.060],
    ['CRWD', 'CrowdStrike',              'NASDAQ', 340, 0.070],
    ['ZS',   'Zscaler',                  'NASDAQ', 220, 0.075],
    ['FTNT', 'Fortinet',                 'NASDAQ',  75, 0.055],
    ['MRVL', 'Marvell Technology',       'NASDAQ',  70, 0.065],
    ['MELI', 'MercadoLibre',             'NASDAQ',2100, 0.055],
    ['REGN', 'Regeneron',                'NASDAQ',1050, 0.040],
    ['GILD', 'Gilead Sciences',          'NASDAQ',  87, 0.038],
    ['BIIB', 'Biogen',                   'NASDAQ', 230, 0.050],
    ['ILMN', 'Illumina',                 'NASDAQ', 130, 0.065],
    ['IDXX', 'IDEXX Laboratories',       'NASDAQ', 480, 0.040],
    ['VRTX', 'Vertex Pharmaceuticals',   'NASDAQ', 490, 0.040],
    ['ALGN', 'Align Technology',         'NASDAQ', 240, 0.060],
    ['DXCM', 'DexCom',                   'NASDAQ',  75, 0.065],
    ['ISRG', 'Intuitive Surgical',       'NASDAQ', 420, 0.040],
    ['HOLX', 'Hologic',                  'NASDAQ',  70, 0.045],
    ['MRNA', 'Moderna',                  'NASDAQ',  65, 0.085],
    ['HOOD', 'Robinhood Markets',        'NASDAQ',  22, 0.100],
    ['COIN', 'Coinbase Global',          'NASDAQ', 195, 0.120],
    ['PLTR', 'Palantir Technologies',    'NASDAQ',  28, 0.100],
    ['RBLX', 'Roblox Corp',              'NASDAQ',  40, 0.100],
    ['SNAP', 'Snap Inc.',                'NASDAQ',  15, 0.120],
    ['LYFT', 'Lyft Inc.',                'NASDAQ',  18, 0.100],
    ['UBER', 'Uber Technologies',        'NASDAQ',  72, 0.060],
    ['ABNB', 'Airbnb',                   'NASDAQ', 150, 0.065],
    ['DASH', 'DoorDash',                 'NASDAQ', 125, 0.080],

    // ── LSE (50) ──────────────────────────────────────────────
    ['SHEL', 'Shell PLC',                   'LSE',  285, 0.040],
    ['AZN',  'AstraZeneca',                 'LSE', 1280, 0.032],
    ['HSBA', 'HSBC Holdings',               'LSE',  720, 0.038],
    ['ULVR', 'Unilever',                    'LSE',  420, 0.025],
    ['BP',   'BP PLC',                      'LSE',  480, 0.045],
    ['GSK',  'GSK PLC',                     'LSE',  175, 0.035],
    ['DGE',  'Diageo',                      'LSE',  280, 0.028],
    ['LSEG', 'London Stock Exchange Group', 'LSE',  980, 0.032],
    ['BARC', 'Barclays',                    'LSE',  230, 0.045],
    ['LLOY', 'Lloyds Banking Group',        'LSE',   55, 0.045],
    ['RIO',  'Rio Tinto',                   'LSE',  540, 0.050],
    ['BHP',  'BHP Group',                   'LSE',  220, 0.048],
    ['GLEN', 'Glencore',                    'LSE',  480, 0.055],
    ['AAL',  'Anglo American',              'LSE',  185, 0.058],
    ['IMB',  'Imperial Brands',             'LSE',  205, 0.025],
    ['BATS', 'British American Tobacco',    'LSE',  270, 0.025],
    ['NG',   'National Grid',               'LSE',  105, 0.022],
    ['REL',  'RELX Group',                  'LSE',  340, 0.028],
    ['SGRO', 'Segro',                       'LSE',   90, 0.040],
    ['LAND', 'Land Securities',             'LSE',   68, 0.040],
    ['BLND', 'British Land',                'LSE',   42, 0.042],
    ['HMSO', 'Hammerson',                   'LSE',   32, 0.055],
    ['IHG',  'InterContinental Hotels',     'LSE',  850, 0.035],
    ['WTB',  'Whitbread',                   'LSE',  320, 0.038],
    ['BRBY', 'Burberry Group',              'LSE',  110, 0.055],
    ['MNDI', 'Mondi',                       'LSE',  128, 0.040],
    ['DS',   'DS Smith',                    'LSE',   42, 0.042],
    ['DLN',  'Derwent London',              'LSE',  255, 0.040],
    ['EXPN', 'Experian',                    'LSE',  320, 0.032],
    ['DPLM', 'Diploma',                     'LSE',  410, 0.038],
    ['AUTO', 'Auto Trader Group',           'LSE',   70, 0.038],
    ['STJ',  "St. James's Place",          'LSE',  140, 0.045],
    ['SMT',  'Scottish Mortgage Trust',     'LSE',   86, 0.055],
    ['ABF',  'Associated British Foods',    'LSE',  185, 0.032],
    ['AHT',  'Ashtead Group',               'LSE',  500, 0.040],
    ['CCH',  'Coca-Cola HBC',               'LSE',  260, 0.028],
    ['ENT',  'Entain PLC',                  'LSE',  123, 0.055],
    ['FLTR', 'Flutter Entertainment',       'LSE',  185, 0.055],
    ['GAW',  'Games Workshop',              'LSE',  950, 0.050],
    ['HL',   'Hargreaves Lansdown',         'LSE',  126, 0.040],
    ['INF',  'Informa',                     'LSE',   78, 0.032],
    ['JD',   'JD Sports Fashion',           'LSE',  145, 0.055],
    ['MKS',  'Marks & Spencer',             'LSE',  360, 0.040],
    ['OCDO', 'Ocado Group',                 'LSE',   42, 0.090],
    ['PSN',  'Persimmon',                   'LSE',   92, 0.050],
    ['RKT',  'Reckitt Benckiser',           'LSE',  650, 0.028],
    ['SBRY', 'J Sainsbury',                 'LSE',   27, 0.035],
    ['SN',   'Smith & Nephew',              'LSE',  152, 0.038],
    ['SPX',  'Spirax Group',                'LSE',  148, 0.038],
    ['SVT',  'Severn Trent',                'LSE',  105, 0.022],

    // ── TSE (50) ──────────────────────────────────────────────
    ['TYT',   'Toyota Motor',           'TSE',  280, 0.035],
    ['SNY',   'Sony Group',             'TSE',  115, 0.045],
    ['SBK',   'SoftBank Group',         'TSE',   75, 0.080],
    ['NTT',   'Nippon Telegraph',       'TSE',  165, 0.025],
    ['NTD',   'Nintendo',               'TSE',  680, 0.050],
    ['FASTR', 'Fast Retailing',         'TSE',  410, 0.040],
    ['KYC',   'Keyence Corp',           'TSE',  580, 0.040],
    ['MTF',   'Mitsubishi UFJ',         'TSE',  135, 0.040],
    ['MBC',   'Mitsubishi Corp',        'TSE',  245, 0.040],
    ['SHC',   'Shin-Etsu Chemical',     'TSE',  580, 0.038],
    ['FNC',   'Fanuc Corp',             'TSE',  400, 0.040],
    ['JRE',   'East Japan Railway',     'TSE',  320, 0.025],
    ['SVI',   'Seven & i Holdings',     'TSE',  210, 0.030],
    ['HIT',   'Hitachi Ltd',            'TSE',  135, 0.040],
    ['DNS',   'Denso Corp',             'TSE',  225, 0.042],
    ['SMC',   'Sumitomo Mitsui',        'TSE',  310, 0.038],
    ['MZH',   'Mizuho Financial',       'TSE',  245, 0.038],
    ['ITC',   'Itochu Corp',            'TSE',  710, 0.035],
    ['KBT',   'Kubota Corp',            'TSE',  205, 0.038],
    ['KMT',   'Komatsu Ltd',            'TSE',  405, 0.040],
    ['CAN',   'Canon Inc.',             'TSE',  395, 0.032],
    ['DSK',   'Daiichi Sankyo',         'TSE',  420, 0.045],
    ['TAK',   'Takeda Pharmaceutical',  'TSE',  385, 0.038],
    ['AST',   'Astellas Pharma',        'TSE',  185, 0.040],
    ['ESI',   'Eisai Co.',              'TSE',  500, 0.050],
    ['JPT',   'Japan Tobacco',          'TSE',  400, 0.025],
    ['ASH',   'Asahi Group',            'TSE',  220, 0.035],
    ['KRN',   'Kirin Holdings',         'TSE',  200, 0.030],
    ['AJN',   'Ajinomoto Co.',          'TSE',  265, 0.032],
    ['KKM',   'Kikkoman Corp',          'TSE',  315, 0.030],
    ['MFD',   'Mitsui Fudosan',         'TSE',  320, 0.035],
    ['SRE',   'Sumitomo Realty',        'TSE',  275, 0.038],
    ['RKN',   'Rakuten Group',          'TSE',   85, 0.085],
    ['CPM',   'Capcom Co.',             'TSE',  305, 0.055],
    ['KNM',   'Konami Group',           'TSE',  645, 0.050],
    ['KDD',   'KDDI Corp',              'TSE',  420, 0.025],
    ['NTX',   'NTT Data Group',         'TSE',  210, 0.035],
    ['BDN',   'Bandai Namco',           'TSE',  365, 0.050],
    ['PNC',   'Panasonic Holdings',     'TSE',  125, 0.040],
    ['OMR',   'Omron Corp',             'TSE',  550, 0.042],
    ['MRB',   'Marubeni Corp',          'TSE',  220, 0.040],
    ['MTS',   'Mitsui & Co.',           'TSE',  620, 0.038],
    ['SMI',   'Sumitomo Corp',          'TSE',  240, 0.038],
    ['OSG',   'Osaka Gas',              'TSE',  195, 0.025],
    ['FJF',   'Fujifilm Holdings',      'TSE',  800, 0.038],
    ['NDC',   'Nidec Corp',             'TSE',  500, 0.055],
    ['DAK',   'Daikin Industries',      'TSE',  175, 0.038],
    ['SCM',   'Secom Co.',              'TSE',  450, 0.028],
    ['RCT',   'Recruit Holdings',       'TSE',  550, 0.040],
    ['YMH',   'Yamaha Motor',           'TSE',  125, 0.045],

    // ── HKEX (50) ─────────────────────────────────────────────
    ['TCT',  'Tencent Holdings',             'HKEX', 380, 0.055],
    ['BABA', 'Alibaba Group',                'HKEX',  85, 0.070],
    ['MTN',  'Meituan',                      'HKEX', 160, 0.065],
    ['HBC',  'HSBC Holdings HK',             'HKEX',  72, 0.038],
    ['AIA',  'AIA Group',                    'HKEX',  62, 0.040],
    ['CHM',  'China Mobile',                 'HKEX',  50, 0.035],
    ['JDH',  'JD.com HK',                   'HKEX', 130, 0.065],
    ['PIN',  'Ping An Insurance',            'HKEX',  45, 0.050],
    ['BYD',  'BYD Company',                  'HKEX', 250, 0.065],
    ['CCB',  'China Construction Bank',      'HKEX',  50, 0.035],
    ['ICB',  'Industrial & Commercial Bank', 'HKEX',  40, 0.032],
    ['BOC',  'Bank of China',                'HKEX',  30, 0.032],
    ['CLI',  'China Life Insurance',         'HKEX',  15, 0.045],
    ['PCN',  'PetroChina',                   'HKEX',  50, 0.045],
    ['CNOC', 'CNOOC Ltd',                    'HKEX',  18, 0.050],
    ['XMI',  'Xiaomi Corp',                  'HKEX',  17, 0.065],
    ['NTE',  'NetEase HK',                   'HKEX', 160, 0.055],
    ['LIN',  'Li Ning',                      'HKEX',  22, 0.065],
    ['SCH',  'Sands China',                  'HKEX',  25, 0.070],
    ['GLE',  'Galaxy Entertainment',         'HKEX',  42, 0.065],
    ['CIS',  'CITIC Securities',             'HKEX',  20, 0.050],
    ['HSB',  'Hang Seng Bank',               'HKEX', 120, 0.030],
    ['SHK',  'Sun Hung Kai Properties',      'HKEX', 112, 0.042],
    ['CKH',  'CK Hutchison Holdings',        'HKEX',  52, 0.040],
    ['PWR',  'Power Assets Holdings',        'HKEX',  58, 0.025],
    ['CLP',  'CLP Holdings',                 'HKEX',  80, 0.022],
    ['MTR',  'MTR Corporation',              'HKEX',  31, 0.025],
    ['HKX',  'HK Exchanges & Clearing',      'HKEX', 330, 0.040],
    ['SWP',  'Swire Pacific',                'HKEX',  16, 0.040],
    ['CPW',  'Cathay Pacific Airways',       'HKEX',   9, 0.065],
    ['HLD',  'Henderson Land Development',   'HKEX',  30, 0.045],
    ['NWD',  'New World Development',        'HKEX',   8, 0.065],
    ['SNL',  'Sino Land',                    'HKEX',  11, 0.042],
    ['WHF',  'Wharf Holdings',               'HKEX',  17, 0.045],
    ['LKR',  'Link REIT',                    'HKEX',  70, 0.030],
    ['FTRE', 'Fortune REIT',                 'HKEX',  11, 0.035],
    ['CTG',  'Country Garden',               'HKEX',   2, 0.150],
    ['EVG',  'Evergrande Group',             'HKEX',   1, 0.200],
    ['VNK',  'China Vanke',                  'HKEX',   8, 0.100],
    ['LGF',  'Longfor Group',                'HKEX',  12, 0.080],
    ['SNC',  'Sunac China',                  'HKEX',   1, 0.180],
    ['CRH',  'China Resources Land',         'HKEX',  40, 0.055],
    ['CIT',  'CITIC Pacific',                'HKEX',   9, 0.050],
    ['NWS',  'NWS Holdings',                 'HKEX',  13, 0.040],
    ['SGS',  'Sino Gas International',       'HKEX',   6, 0.060],
    ['CGH',  'China Gas Holdings',           'HKEX',  13, 0.055],
    ['ENN',  'ENN Energy Holdings',          'HKEX',  60, 0.050],
    ['KNL',  'Kunlun Energy',                'HKEX',   8, 0.055],
    ['TEK',  'Techtronic Industries',        'HKEX',  25, 0.040],
    ['WHL',  'Wheelock & Co.',               'HKEX',  35, 0.040],

    // ── NSE (50) ──────────────────────────────────────────────
    ['RELI',   'Reliance Industries',        'NSE',  280, 0.042],
    ['TCS',    'Tata Consultancy Services',  'NSE',  410, 0.035],
    ['HDFCB',  'HDFC Bank',                  'NSE',  175, 0.038],
    ['INFY',   'Infosys',                    'NSE',  190, 0.040],
    ['ICICIB', 'ICICI Bank',                 'NSE',  130, 0.042],
    ['HUL',    'Hindustan Unilever',         'NSE',  260, 0.028],
    ['AIRTEL', 'Bharti Airtel',              'NSE',  170, 0.045],
    ['ITCL',   'ITC Ltd',                    'NSE',   48, 0.030],
    ['WIPRO',  'Wipro',                      'NSE',   55, 0.045],
    ['HCLT',   'HCL Technologies',           'NSE',  180, 0.040],
    ['AXISB',  'Axis Bank',                  'NSE',  125, 0.045],
    ['KOTAKB', 'Kotak Mahindra Bank',        'NSE',  180, 0.038],
    ['LT',     'Larsen & Toubro',            'NSE',  360, 0.038],
    ['SUNP',   'Sun Pharmaceutical',         'NSE',  170, 0.042],
    ['MARUTI', 'Maruti Suzuki',              'NSE', 1200, 0.038],
    ['BAJFIN', 'Bajaj Finance',              'NSE',  700, 0.050],
    ['TITAN',  'Titan Company',              'NSE',  360, 0.042],
    ['ASPNT',  'Asian Paints',               'NSE',  340, 0.035],
    ['NESTLE', 'Nestle India',               'NSE',  250, 0.028],
    ['PGRID',  'Power Grid Corp',            'NSE',   31, 0.028],
    ['NTPC',   'NTPC',                       'NSE',   37, 0.032],
    ['ONGC',   'ONGC',                       'NSE',   27, 0.048],
    ['TATAST', 'Tata Steel',                 'NSE',  160, 0.058],
    ['TECHM',  'Tech Mahindra',              'NSE',  160, 0.048],
    ['BAJAUTO','Bajaj Auto',                 'NSE',  900, 0.038],
    ['JSWS',   'JSW Steel',                  'NSE',   94, 0.055],
    ['HINDZN', 'Hindustan Zinc',             'NSE',   68, 0.042],
    ['COAL',   'Coal India',                 'NSE',   48, 0.040],
    ['UCEM',   'UltraTech Cement',           'NSE', 1100, 0.038],
    ['GRASIM', 'Grasim Industries',          'NSE',  270, 0.040],
    ['ADANIE', 'Adani Enterprises',          'NSE',  320, 0.075],
    ['ADANIP', 'Adani Ports',                'NSE',  135, 0.065],
    ['ADANIG', 'Adani Green Energy',         'NSE',  190, 0.085],
    ['ADANIT', 'Adani Total Gas',            'NSE',  105, 0.080],
    ['DIVIS',  "Divi's Laboratories",        'NSE',  560, 0.042],
    ['DRRED',  "Dr. Reddy's Laboratories",   'NSE',  680, 0.040],
    ['CIPLA',  'Cipla',                      'NSE',  160, 0.038],
    ['APOLLO', 'Apollo Hospitals',           'NSE',  680, 0.042],
    ['EICHER', 'Eicher Motors',              'NSE',  450, 0.042],
    ['SHREEC', 'Shree Cement',               'NSE', 2800, 0.038],
    ['SBIN',   'State Bank of India',        'NSE',   82, 0.045],
    ['BOB',    'Bank of Baroda',             'NSE',   24, 0.050],
    ['INDUSB', 'IndusInd Bank',              'NSE',  140, 0.050],
    ['HAVL',   'Havells India',              'NSE',  170, 0.042],
    ['DABUR',  'Dabur India',                'NSE',   53, 0.032],
    ['PIDIL',  'Pidilite Industries',        'NSE',  310, 0.038],
    ['GODREJ', 'Godrej Consumer Products',   'NSE',  135, 0.040],
    ['MTRSON', 'Motherson Sumi Systems',     'NSE',   19, 0.055],
    ['TATAM',  'Tata Motors',                'NSE',  100, 0.055],
    ['MHM',    'Mahindra & Mahindra',        'NSE',  290, 0.045],

    // ── CRYPTO (50) ───────────────────────────────────────────
    ['BTC',   'Bitcoin',              'CRYPTO', 6500,  0.060],
    ['ETH',   'Ethereum',             'CRYPTO',  350,  0.070],
    ['BNB',   'BNB',                  'CRYPTO',   58,  0.065],
    ['SOL',   'Solana',               'CRYPTO',  160,  0.080],
    ['XRP',   'XRP',                  'CRYPTO',   0.55,0.075],
    ['DOGE',  'Dogecoin',             'CRYPTO',   0.15,0.100],
    ['ADA',   'Cardano',              'CRYPTO',   0.45,0.080],
    ['TRX',   'TRON',                 'CRYPTO',   0.12,0.070],
    ['AVAX',  'Avalanche',            'CRYPTO',   35,  0.085],
    ['SHIB',  'Shiba Inu (×1000)',    'CRYPTO',   0.002,0.150],
    ['DOT',   'Polkadot',             'CRYPTO',    7,  0.085],
    ['LINK',  'Chainlink',            'CRYPTO',   14,  0.080],
    ['MATIC', 'Polygon',              'CRYPTO',   0.70,0.090],
    ['UNI',   'Uniswap',              'CRYPTO',    8,  0.085],
    ['LTC',   'Litecoin',             'CRYPTO',   85,  0.065],
    ['ATOM',  'Cosmos',               'CRYPTO',    8,  0.085],
    ['XLM',   'Stellar',              'CRYPTO',   0.10,0.080],
    ['FIL',   'Filecoin',             'CRYPTO',    6,  0.090],
    ['NEAR',  'NEAR Protocol',        'CRYPTO',    6,  0.090],
    ['APT',   'Aptos',                'CRYPTO',    8,  0.095],
    ['ARB',   'Arbitrum',             'CRYPTO',    1,  0.100],
    ['OP',    'Optimism',             'CRYPTO',   2.5, 0.100],
    ['HBAR',  'Hedera',               'CRYPTO',   0.10,0.080],
    ['VET',   'VeChain',              'CRYPTO',   0.04,0.090],
    ['ICP',   'Internet Computer',    'CRYPTO',   10,  0.090],
    ['MKR',   'Maker',                'CRYPTO', 2000,  0.070],
    ['AAVE',  'Aave',                 'CRYPTO',   90,  0.075],
    ['CRV',   'Curve DAO',            'CRYPTO',   0.40,0.110],
    ['COMP',  'Compound',             'CRYPTO',   55,  0.080],
    ['SNX',   'Synthetix',            'CRYPTO',    2,  0.110],
    ['GRT',   'The Graph',            'CRYPTO',   0.20,0.100],
    ['ENJ',   'Enjin Coin',           'CRYPTO',   0.30,0.100],
    ['SAND',  'The Sandbox',          'CRYPTO',   0.40,0.110],
    ['MANA',  'Decentraland',         'CRYPTO',   0.35,0.110],
    ['AXS',   'Axie Infinity',        'CRYPTO',    7,  0.100],
    ['GALA',  'Gala',                 'CRYPTO',   0.03,0.130],
    ['IMX',   'Immutable X',          'CRYPTO',    2,  0.110],
    ['ROSE',  'Oasis Network',        'CRYPTO',   0.10,0.120],
    ['FLOW',  'Flow',                 'CRYPTO',   0.80,0.100],
    ['ALGO',  'Algorand',             'CRYPTO',   0.20,0.090],
    ['XTZ',   'Tezos',                'CRYPTO',   0.80,0.085],
    ['EOS',   'EOS',                  'CRYPTO',   0.70,0.090],
    ['ZEC',   'Zcash',                'CRYPTO',   30,  0.080],
    ['TON',   'Toncoin',              'CRYPTO',    5,  0.080],
    ['BCH',   'Bitcoin Cash',         'CRYPTO',  480,  0.070],
    ['SUI',   'Sui',                  'CRYPTO',   1.5, 0.110],
    ['SEI',   'Sei Network',          'CRYPTO',   0.40,0.120],
    ['WLD',   'Worldcoin',            'CRYPTO',    2,  0.110],
    ['PEPE',  'Pepe (×1000)',         'CRYPTO',   0.001,0.180],
    ['FLOKI', 'Floki (×1000)',        'CRYPTO',   0.002,0.170],
];

// ── Build maps ────────────────────────────────────────────────
const STOCKS = STOCKS_RAW.map(([ticker, company, exchange, basePrice, volatility]) => ({
    ticker, company, exchange, basePrice, volatility
}));

const STOCK_MAP = new Map(STOCKS.map(s => [s.ticker, s]));

const EXCHANGE_STOCKS = {};
for (const s of STOCKS) {
    if (!EXCHANGE_STOCKS[s.exchange]) EXCHANGE_STOCKS[s.exchange] = [];
    EXCHANGE_STOCKS[s.exchange].push(s);
}

// ── Price helpers ─────────────────────────────────────────────
const PRICE_STALE_MS = 30 * 60 * 1000; // 30 minutes

function calcNewPrice(currentPrice, basePrice, volatility) {
    const change  = (Math.random() * 2 - 1) * volatility;
    const raw     = currentPrice * (1 + change);
    const min     = basePrice * 0.10;
    const max     = basePrice * 8.00;
    const clamped = Math.max(min, Math.min(max, raw));
    // Use 4dp for tiny prices (crypto penny coins), 2dp otherwise
    return clamped < 1 ? Math.round(clamped * 10000) / 10000 : Math.round(clamped * 100) / 100;
}

function formatChange(changePct) {
    if (changePct === 0) return `0.00%`;
    const sign = changePct > 0 ? '+' : '';
    return `${sign}${changePct.toFixed(2)}%`;
}

function formatPrice(price) {
    return price >= 10
        ? price.toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 })
        : price.toFixed(4);
}

function priceBar(currentPrice, basePrice) {
    const ratio  = Math.min(currentPrice / basePrice, 2);
    const filled = Math.round(ratio * 10);
    const bar    = '█'.repeat(Math.min(filled, 20)) + '░'.repeat(Math.max(0, 20 - filled));
    return `\`${bar}\` ${Math.round(ratio * 100)}% of base`;
}

module.exports = {
    EXCHANGES,
    STOCKS,
    STOCK_MAP,
    EXCHANGE_STOCKS,
    PRICE_STALE_MS,
    calcNewPrice,
    formatChange,
    formatPrice,
    priceBar,
};
